project:
  type: website

website:
  title: "MSS Pipelines Guidance"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorials"
        href: tutorials/index.qmd
      - text: "How-to"
        href: how-to/index.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "Explanation"
        href: explanation/index.qmd
  sidebar:
    style: "docked"
    contents:
      - section: "Tutorials"
        contents:
          - tutorials/index.qmd
      - section: "How-to"
        contents:
          - how-to/index.qmd
      - section: "Reference"
        contents:
          - reference/index.qmd
      - section: "Explanation"
        contents:
          - explanation/index.qmd

format:
  html:
    theme: default
    toc: true
