project:
  type: website

website:
  title: "MSS Pipelines Guidance"
  repo-url: "https://github.com/datasciencecampus/mss-pipelines-guidance"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorials"
        href: tutorials/index.qmd
      - text: "How-to"
        href: how-to/index.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "Explanation"
        href: explanation/index.qmd
    right:
      - icon: github
        href: "https://github.com/datasciencecampus/mss-pipelines-guidance"
        aria-label: "View repository on GitHub"
      - icon: bug
        text: "Report issue"
        href: "https://github.com/datasciencecampus/mss-pipelines-guidance/issues/new/choose"
        aria-label: "Report an issue"
  sidebar:
    style: "docked"
    contents:
      - section: "Tutorials"
        contents:
          - tutorials/index.qmd
      - section: "How-to"
        contents:
          - how-to/index.qmd
      - section: "Reference"
        contents:
          - reference/index.qmd
      - section: "Explanation"
        contents:
          - explanation/index.qmd

format:
  html:
    theme:
      light: simplex
      dark: darkly
    theme-toggle: true
    toc: true
